"""initial schema

Baseline: identical to the schema that db.create_all() produced before
migrations were introduced. Existing databases without an alembic_version
table are stamped with this revision instead of running it (see
app._upgrade_database).

Revision ID: 0001
Revises:
Create Date: 2026-09-15 09:58:14.828979

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('budget_periods',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('monthly_budget', sa.Float(), nullable=False),
    sa.Column('note', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('effective_from')
    )
    op.create_table('category_budgets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('monthly_limit', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('category')
    )
    op.create_table('change_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('op_type', sa.String(length=20), nullable=False),
    sa.Column('description', sa.String(length=300), nullable=True),
    sa.Column('payload_json', sa.Text(), nullable=False),
    sa.Column('undone', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('change_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_change_log_timestamp'), ['timestamp'], unique=False)

    op.create_table('expenses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('store', sa.String(length=100), nullable=False),
    sa.Column('store_detail', sa.String(length=200), nullable=True),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('receipt_samples',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('store', sa.String(length=100), nullable=False),
    sa.Column('image_filename', sa.String(length=255), nullable=False),
    sa.Column('ocr_text', sa.Text(), nullable=True),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.Column('extracted_amount', sa.Float(), nullable=True),
    sa.Column('extracted_date', sa.Date(), nullable=True),
    sa.Column('total_keyword_found', sa.String(length=50), nullable=True),
    sa.Column('amount_on_next_line', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('receipt_samples', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_receipt_samples_store'), ['store'], unique=False)

    op.create_table('store_aliases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alias', sa.String(length=100), nullable=False),
    sa.Column('canonical', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('alias')
    )
    op.create_table('store_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('store', sa.String(length=100), nullable=False),
    sa.Column('total_keywords_json', sa.Text(), nullable=True),
    sa.Column('amount_next_line', sa.Boolean(), nullable=True),
    sa.Column('sample_count', sa.Integer(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('store')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('store_profiles')
    op.drop_table('store_aliases')
    with op.batch_alter_table('receipt_samples', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_receipt_samples_store'))

    op.drop_table('receipt_samples')
    op.drop_table('expenses')
    with op.batch_alter_table('change_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_change_log_timestamp'))

    op.drop_table('change_log')
    op.drop_table('category_budgets')
    op.drop_table('budget_periods')
    # ### end Alembic commands ###
